### ISSUE TITLE
Sauvegarde des niveaux dans des fichier

### ISSUE THREAD

**Issue by matthias4217** [matthias4217/hardcore-rodeo-96#13]
Il faudrait pouvoir écrire les niveaux dans des fichiers, et ne rien avoir en *hardcoded*, pour qu'il soit possible de faire des niveaux de manière assez facile. Cela demande un peu de *parsing*.

**Comment by raphaeltran** [comment]
C'est pas prioritaire, mais effectivement, il faudra absolument un tel système

**Comment by matthias4217** [comment]
Syntaxe : 
  * x pour les SQUARE
  * \ pour les TRIANGLE_DOWN_LEFT
  * / pour les TRIANGLE_DOWN_RIGHT
  * v pour les TRIANGLE_UP_LEFT
  * u pour les TRIANGLE_UP_RIGHT

On pourra ajouter d'autres objets plus tard.

**Comment by matthias4217** [comment]
Les tiles vides peuvent être des espaces ` ` ou des caractères vides ``, lors du *parsing*, pour le passage du fichier texte à la représentation en tableau de caractères. C'est normal, et il faut pouvoir gérer les deux cas.

**Comment by matthias4217** [comment]
Il manque les Collider, et les bonnes textures (qui se positionnent de belle manière), mais on peut considérer cette issue fermée, et en ouvrir d'autres plus spécifiques.
